sudo: false
language: cpp
before_install: 
  - mysql -e "create database IF NOT EXISTS test;" -uroot    
before_script: 
  - git submodule update --init --recursive
  - autoreconf --recursive -if
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - valgrind
      - liburiparser-dev
      - mysql-client 
      - libmysqlclient-dev 
      - sqlite3 
      - libsqlite3-dev 
      - libjson0 
      - libjson0-dev 
      - uuid-dev
script:
  - CXX=g++-4.8 ./configure
  - make test
  - valgrind --leak-check=full --error-exitcode=5 ./tests/arg3_test
 
