language: cpp
before_install: 
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get install mysql-client
    - sudo apt-get install sqlite3
    - mysql -e "create database IF NOT EXISTS test;" -uroot    
before_script: autoreconf -i
install:
  - sudo apt-get install -qq gcc-4.8 g++-4.8 
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - sudo update-alternatives --config gcc
  - sudo update-alternatives --config g++

